import { User, Session } from '@supabase/supabase-js';
import { DbApplication, DbCompany, DbInterview } from '@/types';

export const mockUser: User = {
  id: 'test-user-id-123',
  aud: 'authenticated',
  role: 'authenticated',
  email: 'serdarcill@gmail.com',
  email_confirmed_at: '2026-07-30T12:00:00Z',
  phone: '',
  confirmed_at: '2026-07-30T12:00:00Z',
  last_sign_in_at: '2026-07-31T09:00:00Z',
  app_metadata: { provider: 'email', providers: ['email'] },
  user_metadata: { full_name: 'Serdar Çil' },
  identities: [],
  created_at: '2026-07-30T12:00:00Z',
  updated_at: '2026-07-31T09:00:00Z',
};

export const mockSession: Session = {
  access_token: 'mock-access-token-xyz-123',
  token_type: 'bearer',
  expires_in: 3600,
  refresh_token: 'mock-refresh-token-abc-789',
  user: mockUser,
  expires_at: Math.floor(Date.now() / 1000) + 3600,
};

export const mockApplications: DbApplication[] = [
  {
    id: 'app-1',
    user_id: 'test-user-id-123',
    company_name: 'Trendyol',
    position: 'Frontend Developer',
    status: 'applied',
    priority: 'Orta',
    applied_date: '2026-07-29T10:00:00Z',
    company_id: 'comp-1',
    location: 'İstanbul (Remote)',
    work_type: 'Remote',
    salary: '85,000 TRY',
    notes_count: 1,
    notes: 'Başvuru tamamlandı, HR geri dönüşü bekleniyor.',
    created_at: '2026-07-29T10:00:00Z',
    updated_at: '2026-07-29T10:00:00Z',
  },
  {
    id: 'app-2',
    user_id: 'test-user-id-123',
    company_name: 'Google',
    position: 'Software Engineer',
    status: 'interview',
    priority: 'Kritik',
    applied_date: '2026-07-25T14:00:00Z',
    company_id: 'comp-2',
    location: 'Zürich',
    work_type: 'On-site',
    salary: '140,000 CHF',
    notes_count: 2,
    notes: 'Teknik mülakat planlandı.',
    created_at: '2026-07-25T14:00:00Z',
    updated_at: '2026-07-31T11:00:00Z',
  },
];

export const mockCompanies: DbCompany[] = [
  {
    id: 'comp-1',
    user_id: 'test-user-id-123',
    name: 'Trendyol',
    website: 'https://trendyol.com',
    industry: 'E-Ticaret',
    location: 'İstanbul',
    logo_url: null,
    rating: 4.5,
    notes: 'Büyük e-ticaret firması.',
    is_favorite: true,
    created_at: '2026-07-29T10:00:00Z',
    updated_at: '2026-07-29T10:00:00Z',
  },
  {
    id: 'comp-2',
    user_id: 'test-user-id-123',
    name: 'Google',
    website: 'https://google.com',
    industry: 'Teknoloji',
    location: 'Zürich',
    logo_url: null,
    rating: 5,
    notes: 'Hedef teknoloji devi.',
    is_favorite: true,
    created_at: '2026-07-25T14:00:00Z',
    updated_at: '2026-07-25T14:00:00Z',
  },
];

export const mockInterviews: DbInterview[] = [
  {
    id: 'int-1',
    user_id: 'test-user-id-123',
    application_id: 'app-2',
    company_name: 'Google',
    position: 'Software Engineer',
    stage: 'Teknik Görüşme',
    type: 'Online',
    date: '2026-08-05',
    time: '14:00',
    duration_minutes: 45,
    interviewer_name: 'John Doe',
    interviewer_role: 'Senior SWE',
    meeting_link: 'https://meet.google.com/abc-defg-hij',
    location: null,
    prep_notes: 'Algoritma ve veri yapıları çalışılacak.',
    interview_notes: null,
    result: 'Pending',
    follow_up_date: null,
    created_at: '2026-07-31T11:00:00Z',
    updated_at: '2026-07-31T11:00:00Z',
  },
];
