import { ApplicationStatus, ApplicationStatusConfig } from '../types';

export const STATUS_CONFIG: Record<ApplicationStatus, ApplicationStatusConfig> = {
  saved: {
    id: 'saved',
    label: 'Kaydedildi',
    labelEn: 'Saved',
    bgClass: 'bg-slate-500/10 dark:bg-slate-400/10',
    textClass: 'text-slate-700 dark:text-slate-300',
    borderClass: 'border-slate-300 dark:border-slate-700',
    dotClass: 'bg-slate-400',
    iconName: 'Bookmark',
  },
  applied: {
    id: 'applied',
    label: 'Başvuruldu',
    labelEn: 'Applied',
    bgClass: 'bg-blue-500/10 dark:bg-blue-500/15',
    textClass: 'text-blue-700 dark:text-blue-400',
    borderClass: 'border-blue-300 dark:border-blue-500/30',
    dotClass: 'bg-blue-500',
    iconName: 'Send',
  },
  contacted: {
    id: 'contacted',
    label: 'İletişime Geçildi',
    labelEn: 'Contacted',
    bgClass: 'bg-cyan-500/10 dark:bg-cyan-500/15',
    textClass: 'text-cyan-700 dark:text-cyan-400',
    borderClass: 'border-cyan-300 dark:border-cyan-500/30',
    dotClass: 'bg-cyan-500',
    iconName: 'MessageSquare',
  },
  interview: {
    id: 'interview',
    label: 'Mülakat',
    labelEn: 'Interview',
    bgClass: 'bg-purple-500/10 dark:bg-purple-500/15',
    textClass: 'text-purple-700 dark:text-purple-400',
    borderClass: 'border-purple-300 dark:border-purple-500/30',
    dotClass: 'bg-purple-500',
    iconName: 'Users',
  },
  case_study: {
    id: 'case_study',
    label: 'Vaka Çalışması',
    labelEn: 'Case Study',
    bgClass: 'bg-amber-500/10 dark:bg-amber-500/15',
    textClass: 'text-amber-700 dark:text-amber-400',
    borderClass: 'border-amber-300 dark:border-amber-500/30',
    dotClass: 'bg-amber-500',
    iconName: 'FileCode2',
  },
  offer: {
    id: 'offer',
    label: 'Teklif',
    labelEn: 'Offer',
    bgClass: 'bg-emerald-500/10 dark:bg-emerald-500/15',
    textClass: 'text-emerald-700 dark:text-emerald-400',
    borderClass: 'border-emerald-300 dark:border-emerald-500/30',
    dotClass: 'bg-emerald-500',
    iconName: 'PartyPopper',
  },
  rejected: {
    id: 'rejected',
    label: 'Reddedildi',
    labelEn: 'Rejected',
    bgClass: 'bg-rose-500/10 dark:bg-rose-500/15',
    textClass: 'text-rose-700 dark:text-rose-400',
    borderClass: 'border-rose-300 dark:border-rose-500/30',
    dotClass: 'bg-rose-500',
    iconName: 'XCircle',
  },
};
